### PR TITLE
Cleanup and beautification of newly merged features.

### PR DESCRIPTION
**Pull request by getzdan**
See comments on individual commits in this request for more details.

### CODE REVIEW

**Comment by JobJob** [comment]
:+1:

**Comment by JobJob** [comment]
what is ./create_input.sh (3rd commit message) ?

**Comment by getzdan** [comment]
its a mess. well, have to leave a few of those to measure community involvement :p.
probably should have all commits squashed.

**Comment by JobJob** [comment]
I liked them separate to read, you can squash now if you like

**Pull request merged**
